### ISSUE TITLE
The webview doesn't close when logging out, even with closeOnLoad set to true

### ISSUE THREAD

**Issue by 0xc14m1z** [vmurin/react-native-azure-auth#122] opened 2021-06-16 12:27 UTC
In both Android and iOS, when I try to logout calling `clearSession`, I am able to follow the procedure in the webview, I receive the confirmation from Microsoft but the webview stays open even passing `true` to the `closeOnLoad`.

Trying to manually close it results in a rejection of the promise.

```typescript
const azureAuth = new AzureAuth({
  clientId: "- omissis -"
});

// ...login...

azureAuth.webAuth.clearSession({ closeOnLoad: true })
  .then(() => Alert.alert("Logged out!"))
  .catch((error) => {
    console.error("ERROR", error);
    Alert.alert("Something went wrong 😭")
});
```

I cloned the sample app repo and I can say that it happens there too.

**Comment by vmurin** [comment] 2021-06-18 19:33
Hi,

there are couple of aspects here:

1) closeOnLoad works on iOS only. Android does not have according event.
2) Azure logout procedure currently requires a user interaction - you have to click logout button
3) After clicking logout and manually close the browser window I was always able to logout successfully
I could check it with sample app on android only

**Comment by 0xc14m1z** [comment] 2021-06-21 06:02
Thanks @vmurin for the prompt reply.

I see your point of Azure requiring interactions when logging out, and that's not the issue I'm facing.

The issue I'm having is that if I manually close the page after the logout, I have my promise rejected like the user cancelled the operation. And this happens also in the Android sample app.

**Comment by vmurin** [comment] 2021-06-21 16:37
Couple questions:
- are you testing on device or emulator
- it is  Android? Right?
- Could you please post last screenshot before you closing browser window
- and short description of the way how you are closing the browser

**Comment by 0xc14m1z** [comment] 2021-06-22 05:55
I tested with both iOS and Android, both with real devices.

This is what I see on my Android device, running the sample app, before attempting to close the window:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14879997/122871263-0b36da80-d32f-11eb-8810-bec5ef41e9ba.png)

Thing is that when I click the X icon in the top-left corner of the screen, I can see in the logs that the `clearSession` promise actually rejects:

```
[Tue Jun 22 2021 07:53:10.455]  LOG      {"error": "aa.session.user_cancelled", "error_description": "User cancelled the Auth"}
```

**Comment by vmurin** [comment] 2021-06-26 19:22
It is very strange - on the emulator it works as intended. See screencast


https://user-images.githubusercontent.com/9309490/123523562-92d07080-d6c4-11eb-8206-8dd0b02a8ce5.mp4

**Comment by 0xc14m1z** [comment] 2021-06-28 05:45
I see, that wouldn't be the first time that I experience different behaviors from the emulator and real devices.
Consider that the same happens on a real iPhone, same rejection rather than correctly resolved promise.

**Comment by akshgods** [comment] 2021-07-05 09:46
Im facing same issue, not getting logout from browser.
when im login again it is not asking email and password for login in azure.

**Comment by GeraltRivvia** [comment] 2021-07-27 06:53
Is there no option for the "sign out"web view to automatically close after logging out using a button from the app? I am testing on both simulator and device for iOS.

**Comment by vmurin** [comment] 2021-07-27 17:33
> Is there no option for the "sign out"web view to automatically close after logging out using a button from the app?
> 
> I am testing on both simulator and device for iOS. For B2C sign in, this sign out web view closes and then gets back to the app screen but for non-B2C, you have to manually close the sign out web view screen to get back to the app screen.

Hi, as you mentioned - the logout behavior is very dependent on the Azure-mode and actually controlled mostly by Microsoft logic and not the app. In the non-B2C mode Microsoft page firstly ask you for confirmation of you account, so we may not close the window before you click to confirm. And secondly - the option "closeOnLoad" works only on iOS as the OS has a hook for onPageLoad event and Android don't. So theoretically if you set closeOnLoad=true the browser window should close, but in this case you will not be logged out, as you did not clicked to confirm the logout.

Another possibility - @0xc14m1z may be it is your case - the Azure logout page has some process/request running so the OnPageLoad event never happens.... that's why the window does not close automatically even on iOS.  But it is only suggestion, I did not investigated it.

**Comment by Caipe97** [comment] 2021-08-07 02:26
Is there any workaround to this? I've tested both my implementation and the sample app (following all instructions thoroughly), and I'm not able to log out from my user unless I reload the app (which clears the cache).

**Comment by anujraghuvanshi** [comment] 2022-08-18 07:21
Is there any workarounds which worked for iOS ? 
I was able to fix it for Android. @Elbows 's solution worked perfectly for Android.

But for the iOS, eEven after logout the Webview doesn't close automatically and when doing manual cancel by top right button, It throws `User Canceled` instead if logout was success then it should resolve to success when closing the Webview.

Anybody with any alternative workarounds which can help in getting it working in iOS also.

**Comment by anujraghuvanshi** [comment] 2022-08-18 12:54
@0xc14m1z - I am having exactly the same issue as you have mentioned. Did you get any solution?

**Comment by 0xc14m1z** [comment] 2022-08-18 13:21
Unfortunately we changed library completely. We used the one used by Microsoft in their tutorials, `react-native-app-auth`.

**Comment by anujraghuvanshi** [comment] 2022-08-18 13:31
Thanks for suggestions @0xc14m1z . So the library which you mentioned working fine with all cases in both platforms (Android & iOS) ?

**Comment by 0xc14m1z** [comment] 2022-08-18 13:32
Yep @anujraghuvanshi

**Comment by anujraghuvanshi** [comment] 2022-08-29 11:05
@0xc14m1z  I have tried using `react-native-app-auth` package for it. Somehow with `react-native-azure-auth` I am getting the scopes data but with App Auth package, I am not getting the scopes data. Did you face any such issue with that of if you have any resolutions for same ?

**Comment by anujraghuvanshi** [comment] 2022-09-02 06:21
Is anybody here with a fix on logout stuff?

While doing Signout, When the signout window opens, Whether I sign out the logged-in user Or close the window before logging out. It throws `User cancelled` error. Which should not happen. When doing actual logout, It should return with properly identifiable response.

**Comment by vmurin** [comment] 2022-10-03 20:34
should be fixed with release 1.8.4

**Closed by vmurin** 2022-10-03 20:34 UTC

**Comment by bibekgurunguh** [comment] 2022-11-15 12:07
> should be fixed with release 1.8.4

It still persists on v 1.8.4 on iOS

**Comment by paulschoen** [comment] 2023-06-15 21:45
This issue is still persisting v1.8.8 for iOS.

**Comment by Akshay-Katariya** [comment] 2023-07-03 14:25
This works fine in Android but in iOS we are still stuck on WebView 
`"react-native-azure-auth": "^1.8.8"`

**Comment by andresfelipe9619** [comment] 2023-07-27 03:54
Persisting…

**Comment by NadiaMit** [comment] 2023-08-11 14:38
@0xc14m1z I tried using `react-native-app-auth` before this library, but i wasn't able to aquire the token silently/create a silent login. How are you doing this?

**Comment by NadiaMit** [comment] 2023-08-11 14:39
Has anybody found a workaround for this yes?
