### ISSUE TITLE
Token is not clearing in Android emulator after app uninstall

### ISSUE THREAD

**Issue by suresh777** [vmurin/react-native-azure-auth#46] opened 2019-10-24 15:53 UTC
I integrated this plugin it is working fine in ios and android.In android I am able to run and done successful login. After that i uninstalled the app from emulator and try to run again and clicking on login it is going to silent login.i kept backup= false in android manifest still it is storing token in async storage.

**Comment by vmurin** [comment] 2019-10-24 16:41
You are right - currently there is no such feature like "clear all cached data"

I will think about possible implementation, so that you kann add it to the `PACKAGE_REMOVED` listener

**Comment by suresh777** [comment] 2019-10-25 04:55
Are you storing token in async storage or somewhere. If you are store in async storage it will be cleared after uninstall.

**Comment by vmurin** [comment] 2019-10-25 14:35
In have today published new version with the new method `clearPersistentCache` ([link](https://vmurin.github.io/react-native-azure-auth/Auth.html))
You can use it on your own. And on uninstall cached in AsyncStorage data will be cleared as well (as you wrote)

So I close this issue.

**Closed by vmurin** 2019-10-25 14:35 UTC

**Comment by suresh777** [comment] 2019-10-29 09:39
i have taken your latest plugin afterthat i logged in and uninstalled the app. Again i installed the app i am able to see previous user login details.

**Comment by vmurin** [comment] 2019-10-29 22:07
Where and how you can see the user login details? Which details you see?

**Comment by suresh777** [comment] 2019-10-31 12:31
I am able to see emailid and it is showing message like "Are you trying to sign in myapp?". If i press yes it is doing silent login without my password.

**Comment by vmurin** [comment] 2019-11-12 21:01
Just what additionally comment this issue to clear the behavior.
The library uses system browser (different components on iOS and Android but with similar behavior) to login into the app. There is a number of reasons to do so. A good explanation you can find for example [here](https://developer.chrome.com/multidevice/android/customtabs#whentouse).

If you uninstall your app it does affect of course the system browser component. And if you reinstall the app und login shortly after that, the browser component uses saved cookies to re-login into Azure. 
There is no security breach, this is intended behavior as long as the tokens saved in cookie are valid. The cookie tokens are short-lived, usually not longer as 1 hour. After this period of time the user will be re-prompted to enter his password.
