### ISSUE TITLE
Question/Feature: Force choosing user on each login attempt

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#52] opened 2019-11-21 14:33 UTC
Hi!

There is an issue where if the user has successfully signed in on micorsoft – it then not possible to switch to another user - see here the screen on Microsoft page: there is no option here to select a different user

Is there any way to clear the cache so each time the user will be taken to manage users screen? I have tried the `azureAuth.webAuth.clearSession()`, but this only seems to clear the token

![image](https://user-images.githubusercontent.com/1477963/69347074-8da37800-0c7c-11ea-88bc-51bac08c9ae2.png)

**Comment by vmurin** [comment] 2019-11-21 14:43
Hi,

this is a duplicate of the issue #32 
The problem exists on iOS only. The reason - Azure logout is interactive now. You should select the account to logout and not only navigate to logout link. By default clearSession() closes the browser window after the logout URL is loaded successfully.
So take a look at the two last comments in the issue #32 and choose one of the proposed solutions

**Closed by vmurin** 2019-11-21 14:43 UTC

**Comment by oferRounds** [comment] 2019-11-21 14:49
Ok, will do – thanks!
Also, I think I noticed an error on this line: https://github.com/vmurin/react-native-azure-auth/blob/640c62b53c6f3b9c849a8f5f5b276a4c740444ad/src/auth/index.js#L247

Should be: `this.cache.removeToken`

**Comment by oferRounds** [comment] 2019-11-21 14:49
By the way – it‘s not only on iOS, we got the same problem also on Android

**Comment by oferRounds** [comment] 2019-11-21 14:53
There’s still might be a problem with this solution – as it might be that the user was successfully logged in on Microsoft, but was not authorized on app’s server. In this case, it get stuck a bit in the middle

Isn’t there any way to force re-choosing the user?

**Comment by oferRounds** [comment] 2019-11-21 14:54
Also, getting the error: `Cannot use 'in' operator to search for 'closeOnLoad' in shuki@oridemobob.onmicrosoft.com`

**Comment by oferRounds** [comment] 2019-11-21 14:56
> You should select the account to logout 
that means the email?

**Comment by vmurin** [comment] 2019-11-21 15:14
-  See my screenshots of logout screen on android - similar screen as you posted here, but with logout question. After correct logout you will be prompted for login as in the first time
- Thank you very much for the bug reporting! (removeToken)
- to force user to login just call with `prompt` parameter - see #32 last comment
- the last error caused by wrong parameters by clearSession call

I will push this changes in a couple minutes:

- add clearSession param check
- bugfix removeToken

**Comment by oferRounds** [comment] 2019-11-21 16:12
Thank you @vmurin for your quick response!

Looking on #32’s last comment – I couldn’t find the example, and not actually sure about the prompt param
Would you be able to paste a snippet here?

**Comment by oferRounds** [comment] 2019-11-21 16:24
I think I found it! You mean like this?:
`azureAuth.webAuth.authorize({ scope: 'openid', prompt: 'login' })`

**Comment by vmurin** [comment] 2019-11-21 16:45
Hey, I'm very sorry ! I messed the issue number! It is #51 - there you'll see screenshots and call example.

**Comment by ironmanromeo** [comment] 2020-09-10 09:56
> I think I found it! You mean like this?
> `azureAuth.webAuth.authorize({ scope: 'openid', prompt: 'login' })`

Solved adding - prompt: 'login' - to 

> `azureAuth.webAuth.authorize({ scope: 'xxxxxx', prompt: 'login' })`

Thank you so much!

**Comment by ironmanromeo** [comment] 2020-09-10 10:12
vmurin: I think you should add it to instructions or set by default. Thanks.

Romeo

**Comment by vmurin** [comment] 2020-09-10 18:03
> vmurin: I think you should add it to instructions or set by default. Thanks.
> 
> Romeo

Hi Romeo,

thank you for your feedback. 
Each app has own use cases and the one of it is if user just want to re-login.  That's why I did not add it as default.

Vladimir
