### ISSUE TITLE
First user login token is not clearing

### ISSUE THREAD

**Issue by ranshine** [vmurin/react-native-azure-auth#59] opened 2019-11-29 07:14 UTC
I am trying do multiple users login. So first i logged in with some userid after that i logged out. Now i am logged with different userid. After some time  if i do logout trying to login again the web url showing two users login ids. If i click on previous user login it is doing successful login. That means previous user login session is not clearing.

**Comment by ranshine** [comment] 2019-11-29 09:29
I am getting sometimes this crash when click on previous user login
![Simulator Screen Shot - iPhone X - 2019-11-29 at 14 57 27](https://user-images.githubusercontent.com/25414755/69858821-d54b8480-12b8-11ea-8052-a8c30ce9ae41.png)

**Comment by vmurin** [comment] 2019-11-29 22:21
Duplicate of the issue #51 

Take a look on the last [comment](https://github.com/vmurin/react-native-azure-auth/issues/51#issuecomment-553295704) there. There are two options to solve you issue.

**Comment by ranshine** [comment] 2019-12-12 09:25
Even i use below line code, It is showing two users on microsoft web page. If i tap on previous user login it is generating token.
let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read', prompt: 'login'})

Event after logging out first user using your clear session. It is still maintaining in browser

**Comment by vmurin** [comment] 2019-12-18 07:18
Have you tried this?
```js

...
azureAuth.webAuth
    .clearSession({closeOnLoad: false})
...
```

Some time ago MS added promt to confirm logout and now you should do logout interactively to clear auth cookies.

**Comment by suresh777** [comment] 2019-12-18 07:38
Yes before logging into second user i am clearing session

**Comment by vmurin** [comment] 2019-12-18 07:39
Do you see the logout prompt?

**Comment by suresh777** [comment] 2019-12-20 13:39
Yes now it is working after doing this
 azureAuth.webAuth
    .clearSession({closeOnLoad: false})

**Comment by vmurin** [comment] 2019-12-26 21:29
👍

**Closed by vmurin** 2019-12-26 21:29 UTC
Labels: good first issue
